# Generated by Django 3.1.7 on 2021-03-30 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searched_keyword', models.TextField()),
                ('search_time', models.DateTimeField(auto_now=True)),
                ('search_result', models.JSONField()),
                ('user_ip_address', models.CharField(max_length=50)),
                ('user_browser_details', models.CharField(max_length=500)),
                ('user_location', models.CharField(max_length=255)),
                ('visited_sites', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
