# Generated by Django 3.1.7 on 2021-03-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersearchhistory',
            old_name='user_location',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='usersearchhistory',
            old_name='user_browser_details',
            new_name='user_browser',
        ),
        migrations.AddField(
            model_name='usersearchhistory',
            name='country',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
