# Generated by Django 3.1.7 on 2021-03-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_history', '0002_auto_20210331_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersearchhistory',
            name='keyword_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
