# Generated by Django 3.1.7 on 2021-03-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_history', '0003_usersearchhistory_keyword_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersearchhistory',
            name='country_slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersearchhistory',
            name='user_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
