# Generated by Django 3.1.7 on 2021-03-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_history', '0004_auto_20210331_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearchhistory',
            name='search_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
